# Generated by Django 3.0.8 on 2020-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageK', '0002_auto_20200729_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='Image1', max_length=200),
            preserve_default=False,
        ),
    ]
