# Generated by Django 3.0.8 on 2020-07-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageK', '0004_auto_20200730_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
